# Generated by Django 5.1.1 on 2024-09-18 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votos', '0002_persona_fecha_nacimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='fecha_alta',
            field=models.DateField(verbose_name='Fecha de Publicación'),
        ),
    ]
